#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on %(date)s

@author: %(Ashfaq)s
"""

def Power_xn(x, n):
    def helper(x, n):
        while n >= 1:
            if x == 0:
                return 0
            if n == 0:
                return 1
            if n == 1:
                return x
            if n%2 == 0:
                return Power_xn(x, n/2) * Power_xn(x, n/2)
            else:
                return Power_xn(x, n//2) * Power_xn(x, n//2) * x
    res = helper(x, abs(n)) 
    return res if n > 0 else 1/res
            
        
    

x = 2.00000
n = -2
Power_xn(x, n)